name: Publish Package
env:
   NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

on:
  pull_request:
    branches: [master] 
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [14.x]
    
    steps:
      - name: Checkout staging
        uses: actions/checkout@v2
        
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: Installing packages
        run: yarn install

      - name: Installing packages
        run: yarn build

      - name: Publish package
        run: npm publish